set(ISL_CXX_INSTALL_ROOT "" CACHE STRING "Location of ISL-C++ bindings installation")

FIND_PATH(ISL_CXX_INCLUDE_DIR Aff.h HINTS ${ISL_CXX_INSTALL_ROOT}/include)
FIND_LIBRARY(ISL_CXX_LIBRARY isl-cxx HINTS ${ISL_CXX_INSTALL_ROOT}/lib)

IF (ISL_CXX_INCLUDE_DIR AND ISL_CXX_LIBRARY)
  SET(ISL_CXX_FOUND TRUE)
ENDIF (ISL_CXX_INCLUDE_DIR AND ISL_CXX_LIBRARY)

IF (ISL_CXX_FOUND)
  IF (NOT ISL_CXX_FIND_QUIETLY)
    MESSAGE(STATUS "Found Isl C++ bindings: ${ISL_CXX_LIBRARY}")
  ENDIF (NOT ISL_CXX_FIND_QUIETLY)
ELSE (ISL_CXX_FOUND)
  IF (ISL_CXX_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Isl C++ bindings")
  ENDIF (ISL_CXX_FIND_REQUIRED)
ENDIF (ISL_CXX_FOUND)

