FIND_PATH(PAPI_INCLUDE_DIR pluto/libpluto.h)

FIND_LIBRARY(PAPI_LIBRARY NAMES pluto)

IF (PAPI_INCLUDE_DIR AND PAPI_LIBRARY)
  SET(PAPI_FOUND TRUE)
ENDIF (PAPI_INCLUDE_DIR AND PAPI_LIBRARY)


IF (PAPI_FOUND)
  IF (NOT PAPI_FIND_QUIETLY)
    MESSAGE(STATUS "Found Papi: ${PAPI_LIBRARY}")
  ENDIF (NOT PAPI_FIND_QUIETLY)
ELSE (PAPI_FOUND)
  IF (PAPI_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Papi")
  ENDIF (PAPI_FIND_REQUIRED)
ENDIF (PAPI_FOUND)

