set(PQXX_INSTALL_ROOT "" CACHE STRING "Location of PQXX installation")

FIND_PATH(PQXX_INCLUDE_DIR pqxx HINTS ${PQXX_INSTALL_ROOT}/include)
FIND_LIBRARY(PQXX_LIBRARY pqxx HINTS ${PQXX_INSTALL_ROOT}/lib)

IF (PQXX_INCLUDE_DIR AND PQXX_LIBRARY)
  SET(PQXX_FOUND TRUE)
ENDIF (PQXX_INCLUDE_DIR AND PQXX_LIBRARY)


IF (PQXX_FOUND)
  IF (NOT PQXX_FIND_QUIETLY)
    MESSAGE(STATUS "Found PQxx: ${PQXX_LIBRARY}")
  ENDIF (NOT PQXX_FIND_QUIETLY)
ELSE (PQXX_FOUND)
  IF (PQXX_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find PQxx")
  ENDIF (PQXX_FIND_REQUIRED)
ENDIF (PQXX_FOUND)
