if (NOT ISL_FOUND)
  set(ISL_INSTALL_ROOT "" CACHE STRING "Location of ISL installation")

  FIND_PATH(ISL_INCLUDE_DIR isl/aff.h HINTS ${ISL_INSTALL_ROOT}/include)
  FIND_LIBRARY(ISL_LIBRARY NAMES libisl.so libisl.a HINTS ${ISL_INSTALL_ROOT}/lib)

  IF (ISL_INCLUDE_DIR AND ISL_LIBRARY)
    SET(ISL_FOUND TRUE)
  ENDIF (ISL_INCLUDE_DIR AND ISL_LIBRARY)


  IF (ISL_FOUND)
    IF (NOT Isl_FIND_QUIETLY)
      MESSAGE(STATUS "Found Isl: ${ISL_LIBRARY}")
    ENDIF (NOT Isl_FIND_QUIETLY)
  ELSE (ISL_FOUND)
    IF (Isl_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Isl")
    ENDIF (Isl_FIND_REQUIRED)
  ENDIF (ISL_FOUND)
endif (NOT ISL_FOUND)
