if (NOT ISL_FOUND)
  set(ISL_INSTALL_ROOT "" CACHE STRING "Location of ISL installation")

  FIND_PATH(ISL_INCLUDE_DIR isl/aff.h HINTS ${ISL_INSTALL_ROOT}/include)

  IF (ISL_INCLUDE_DIR)
    SET(ISL_FOUND TRUE)
  ENDIF (ISL_INCLUDE_DIR)

  IF (ISL_FOUND)
    IF (NOT Isl_FIND_QUIETLY)
      MESSAGE(STATUS "Found Isl headers.")
    ENDIF (NOT Isl_FIND_QUIETLY)
  ELSE (ISL_FOUND)
    IF (Isl_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Isl headers.")
    ENDIF (Isl_FIND_REQUIRED)
  ENDIF (ISL_FOUND)
endif (NOT ISL_FOUND)
