set(POLLY_INSTALL_ROOT "" CACHE STRING "Location of Polly installation")

FIND_PATH(POLLY_INCLUDE_DIR polly/LinkAllPasses.h
  HINTS ${POLLY_INSTALL_ROOT}/include/ ${POLLY_INSTALL_ROOT}/tools/polly/include)
FIND_LIBRARY(POLLY_LIBRARY NAMES libPolly.so HINTS ${POLLY_INSTALL_ROOT}/lib)

IF (POLLY_INCLUDE_DIR AND POLLY_LIBRARY)
  SET(POLLY_FOUND TRUE)
ENDIF (POLLY_INCLUDE_DIR AND POLLY_LIBRARY)

IF (POLLY_FOUND)
  IF (NOT POLLY_FIND_QUIETLY)
    MESSAGE(STATUS "Found Polly: ${POLLY_LIBRARY}")
  ENDIF (NOT POLLY_FIND_QUIETLY)
ELSE (POLLY_FOUND)
  IF (POLLY_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Polly")
  ENDIF (POLLY_FIND_REQUIRED)
ENDIF (POLLY_FOUND)

