set(POLLY_INSTALL_ROOT "${LLVM_INSTALL_ROOT}" CACHE STRING "Location of Polly installation")

FIND_PATH(POLLY_INCLUDE_DIRS polly/LinkAllPasses.h
  PATHS
    ${POLLY_INSTALL_ROOT}/include/
    ${POLLY_INSTALL_ROOT}/tools/polly/include/
)
FIND_PATH(POLLY_ISL_INCLUDE_DIRS polly/isl/isl-noexceptions.h
  PATHS
    ${POLLY_INSTALL_ROOT}/include/
    ${POLLY_INSTALL_ROOT}/tools/polly/include/
)

FIND_LIBRARY(POLLY_LIBRARY lib
  NAMES
    libPolly.so
    libPolly.a PATHS ${POLLY_INSTALL_ROOT}/lib/)

IF (POLLY_ISL_INCLUDE_DIRS AND
    POLLY_INCLUDE_DIRS AND
    POLLY_LIBRARY)
  SET(Polly_FOUND TRUE)
ENDIF (POLLY_ISL_INCLUDE_DIRS AND
       POLLY_INCLUDE_DIRS AND
       POLLY_LIBRARY)

IF (Polly_FOUND)
  IF (NOT Polly_FIND_QUIETLY)
    MESSAGE(STATUS "Found Polly: ${POLLY_LIBRARY}")
  ENDIF (NOT Polly_FIND_QUIETLY)
  get_filename_component(POLLY_LIBRARY_DIRS ${POLLY_LIBRARY} DIRECTORY)
ELSE (Polly_FOUND)
  IF (Polly_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Polly")
  ENDIF (Polly_FIND_REQUIRED)
ENDIF (Polly_FOUND)
