set(PTHREAD_INSTALL_ROOT "" CACHE STRING "Location of PTHREAD installation")

FIND_PATH(PTHREAD_INCLUDE_DIR pthread.h HINTS ${PTHREAD_INSTALL_ROOT}/include)
FIND_LIBRARY(PTHREAD_LIBRARY pthread HINTS ${PTHREAD_INSTALL_ROOT}/lib)

IF (PTHREAD_INCLUDE_DIR AND PTHREAD_LIBRARY)
  SET(PTHREAD_FOUND TRUE)
ENDIF (PTHREAD_INCLUDE_DIR AND PTHREAD_LIBRARY)


IF (PTHREAD_FOUND)
  IF (NOT PTHREAD_FIND_QUIETLY)
    MESSAGE(STATUS "Found Pthread: ${PTHREAD_LIBRARY}")
  ENDIF (NOT PTHREAD_FIND_QUIETLY)
ELSE (PTHREAD_FOUND)
  IF (PTHREAD_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Pthread")
  ENDIF (PTHREAD_FIND_REQUIRED)
ENDIF (PTHREAD_FOUND)
