set(PAPI_INSTALL_ROOT "" CACHE STRING "Location of PAPI installation")

FIND_PATH(PAPI_INCLUDE_DIR papi.h HINTS ${PAPI_INSTALL_ROOT}/include)
FIND_LIBRARY(PAPI_LIBRARY papi HINTS ${PAPI_INSTALL_ROOT}/lib)

IF (PAPI_INCLUDE_DIR AND PAPI_LIBRARY)
  SET(PAPI_FOUND TRUE)
ENDIF (PAPI_INCLUDE_DIR AND PAPI_LIBRARY)


IF (PAPI_FOUND)
  IF (NOT PAPI_FIND_QUIETLY)
    MESSAGE(STATUS "Found Papi: ${PAPI_LIBRARY}")
  ENDIF (NOT PAPI_FIND_QUIETLY)
ELSE (PAPI_FOUND)
  IF (PAPI_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Papi")
  ENDIF (PAPI_FIND_REQUIRED)
ENDIF (PAPI_FOUND)

